version: 1

services:
  - type: web
    name: django-portfoliosite
    env: python
    build:
      docker:
        dockerfile: Dockerfile
        context: .
      args:
        DEV: "false"
    environment:
      DB_HOST: your-database-host
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
    plan: starter
    routes:
      - path: /
        type: http
        port: 8000
